// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gig.proto

package gig_platform_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gig) Reset() {
	*x = Gig{}
	mi := &file_gig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gig) ProtoMessage() {}

func (x *Gig) ProtoReflect() protoreflect.Message {
	mi := &file_gig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gig.ProtoReflect.Descriptor instead.
func (*Gig) Descriptor() ([]byte, []int) {
	return file_gig_proto_rawDescGZIP(), []int{0}
}

func (x *Gig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetGigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GigId         string                 `protobuf:"bytes,1,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGigRequest) Reset() {
	*x = GetGigRequest{}
	mi := &file_gig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGigRequest) ProtoMessage() {}

func (x *GetGigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGigRequest.ProtoReflect.Descriptor instead.
func (*GetGigRequest) Descriptor() ([]byte, []int) {
	return file_gig_proto_rawDescGZIP(), []int{1}
}

func (x *GetGigRequest) GetGigId() string {
	if x != nil {
		return x.GigId
	}
	return ""
}

type GetGigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gig           *Gig                   `protobuf:"bytes,1,opt,name=gig,proto3" json:"gig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGigResponse) Reset() {
	*x = GetGigResponse{}
	mi := &file_gig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGigResponse) ProtoMessage() {}

func (x *GetGigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGigResponse.ProtoReflect.Descriptor instead.
func (*GetGigResponse) Descriptor() ([]byte, []int) {
	return file_gig_proto_rawDescGZIP(), []int{2}
}

func (x *GetGigResponse) GetGig() *Gig {
	if x != nil {
		return x.Gig
	}
	return nil
}

var File_gig_proto protoreflect.FileDescriptor

const file_gig_proto_rawDesc = "" +
	"\n" +
	"\tgig.proto\"\x1b\n" +
	"\x03Gig\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"&\n" +
	"\rGetGigRequest\x12\x15\n" +
	"\x06gig_id\x18\x01 \x01(\tR\x05gigId\"(\n" +
	"\x0eGetGigResponse\x12\x16\n" +
	"\x03gig\x18\x01 \x01(\v2\x04.GigR\x03gig27\n" +
	"\n" +
	"GigService\x12)\n" +
	"\x06GetGig\x12\x0e.GetGigRequest\x1a\x0f.GetGigResponseB'Z%github.com/vsayfb/gig-platform-protosb\x06proto3"

var (
	file_gig_proto_rawDescOnce sync.Once
	file_gig_proto_rawDescData []byte
)

func file_gig_proto_rawDescGZIP() []byte {
	file_gig_proto_rawDescOnce.Do(func() {
		file_gig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gig_proto_rawDesc), len(file_gig_proto_rawDesc)))
	})
	return file_gig_proto_rawDescData
}

var file_gig_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gig_proto_goTypes = []any{
	(*Gig)(nil),            // 0: Gig
	(*GetGigRequest)(nil),  // 1: GetGigRequest
	(*GetGigResponse)(nil), // 2: GetGigResponse
}
var file_gig_proto_depIdxs = []int32{
	0, // 0: GetGigResponse.gig:type_name -> Gig
	1, // 1: GigService.GetGig:input_type -> GetGigRequest
	2, // 2: GigService.GetGig:output_type -> GetGigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gig_proto_init() }
func file_gig_proto_init() {
	if File_gig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gig_proto_rawDesc), len(file_gig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gig_proto_goTypes,
		DependencyIndexes: file_gig_proto_depIdxs,
		MessageInfos:      file_gig_proto_msgTypes,
	}.Build()
	File_gig_proto = out.File
	file_gig_proto_goTypes = nil
	file_gig_proto_depIdxs = nil
}
