// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: gig.proto

package gig_platform_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GigService_GetGig_FullMethodName = "/GigService/GetGig"
)

// GigServiceClient is the client API for GigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GigServiceClient interface {
	GetGig(ctx context.Context, in *GetGigRequest, opts ...grpc.CallOption) (*GetGigResponse, error)
}

type gigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGigServiceClient(cc grpc.ClientConnInterface) GigServiceClient {
	return &gigServiceClient{cc}
}

func (c *gigServiceClient) GetGig(ctx context.Context, in *GetGigRequest, opts ...grpc.CallOption) (*GetGigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGigResponse)
	err := c.cc.Invoke(ctx, GigService_GetGig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GigServiceServer is the server API for GigService service.
// All implementations must embed UnimplementedGigServiceServer
// for forward compatibility.
type GigServiceServer interface {
	GetGig(context.Context, *GetGigRequest) (*GetGigResponse, error)
	mustEmbedUnimplementedGigServiceServer()
}

// UnimplementedGigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGigServiceServer struct{}

func (UnimplementedGigServiceServer) GetGig(context.Context, *GetGigRequest) (*GetGigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGig not implemented")
}
func (UnimplementedGigServiceServer) mustEmbedUnimplementedGigServiceServer() {}
func (UnimplementedGigServiceServer) testEmbeddedByValue()                    {}

// UnsafeGigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GigServiceServer will
// result in compilation errors.
type UnsafeGigServiceServer interface {
	mustEmbedUnimplementedGigServiceServer()
}

func RegisterGigServiceServer(s grpc.ServiceRegistrar, srv GigServiceServer) {
	// If the following call panics, it indicates UnimplementedGigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GigService_ServiceDesc, srv)
}

func _GigService_GetGig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GigServiceServer).GetGig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GigService_GetGig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GigServiceServer).GetGig(ctx, req.(*GetGigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GigService_ServiceDesc is the grpc.ServiceDesc for GigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GigService",
	HandlerType: (*GigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGig",
			Handler:    _GigService_GetGig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gig.proto",
}
